Do not validate pickings already done. (#1110)
Otherwise
odoo.exceptions.UserError: ('You cannot validate a transfer if no quantites are reserved nor done. To force the transfer, switch in edit more and encode the done quantities.', '')