FIX l10n_it_website_portal_fatturapa_sale
Accessing to online quote with anonymous:
odoo.exceptions.AccessError: ('The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: Contact, Operation: read) - (Records: [7], User: 4)', None)
Error to render compiling AST
AccessError: ('The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: Contact, Operation: read) - (Records: [7], User: 4)', None)
Template: payment.payment_tokens_list
Path: /templates/t/form/div[2]/label/input
Node: <input type="checkbox" name="electronic_invoice_subjected" t-att-checked="'checked' if request.env['res.partner'].browse(partner_id).electronic_invoice_subjected else None"/>
                    I request to receive electronic invoice - - -

Refactored without nested ajax calls to get more control and handle anonymous requests

Add support for signature flow