[FIX] l10n_it_withholding_tax: document_tax_totals needs to be declared primary in oder to be inherited Without this, SO and PO pdf reports (which are using it to display tax totals) raise an error as follows:
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
KeyError: 'o'
Template: account.document_tax_totals
Path: /t/t[3]/tr[1]/td[2]/span
Node: <span t-field="o.withholding_tax_amount" t-options="{\'widget\': \'monetary\', \'display_currency\': o.currency_id}"/>