[FIX] l10n_it_fatturapa_out: DatiRiepilogo is mandatory but tax_line_ids is not required (#1226)
Without this, when generating the e-invoice for an invoice that has no tax lines, the following exception is raised:
IncompleteElementContentError: (<odoo.addons.l10n_it_fatturapa.bindings.fatturapa_v_1_2.DatiBeniServiziType object at 0x7f6fb8653ad0>, <pyxb.utils.fac.Configuration object at 0x7f6fb7d137d0>, [<pyxb.binding.basis.ElementContent object at 0x7f6fb8168410>, <pyxb.binding.basis.ElementContent object at 0x7f6fb8168350>, <pyxb.binding.basis.ElementContent object at 0x7f6fb87d8c90>], {})