[FIX] l10n_it_vat_registries: Missing method _l10n_it_get_tax_kind
The method has been removed from Odoo core in https://github.com/odoo/odoo/commit/0f66a0caa1034bf55607579363409ed024e27495.
Without this change, the following is raised:
AttributeError: 'account.tax' object has no attribute '_l10n_it_get_tax_kind'