[l10n_it_ddt] Fix display_name: otherwise name is shown as False in case not name
[l10n_it_ddt] Hide name in ddt.stock.picking.package.preparation.form as useless

[l10n_it_ddt] Hide Operations page in ddt_stock_picking_package_preparation_form as useless

[l10n_it_ddt] Improve _compute_display_name method

[l10n_it_ddt] Add ddt_ids to stock.picking.tree

[l10n_it_ddt] Add check_linked_picking method to stock.picking.package.preparation to check if selected picking is already linked to DDT

[l10n_it_ddt] Change action_stock_picking_package_preparation name to DDT
I use this work around to fix translation issue: only updating the name needs to manually add entry to po file that would be conflict with transifex sync script.
I also tried to delete orginal menuitem but after every update I get the following error:

ValueError: External ID not found in the system: stock_picking_package_preparation.menu_stock_picking_package_preparation

So I chose to get original menuitem only visibile to admin!