[FIX] l10n_it_fatturapa_out: fix test 'test_multicompany_fail' added 'with_company()' instead of putting the company in 'copy()'
https://github.com/OCA/l10n-italy/actions/runs/4082549051/jobs/7037035918#step:8:381
Traceback (most recent call last):
  File "/__w/l10n-italy/l10n-italy/l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py", line 816, in test_multicompany_fail
    product2 = self.product_product_10.copy(
  File "/opt/odoo/addons/product/models/product_product.py", line 393, in copy
    template = self.product_tmpl_id.copy(default=default)
  File "/opt/odoo/addons/stock/models/product.py", line 878, in copy
    res = super().copy(default=default)
  File "/opt/odoo/addons/product/models/product_template.py", line 474, in copy
    return super(ProductTemplate, self).copy(default=default)
  File "/opt/odoo/odoo/models.py", line 4776, in copy
    record_copy = self.create(vals)
  File "<decorator-gen-169>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 409, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/addons/product/models/product_template.py", line 428, in create
    templates = super(ProductTemplate, self).create(vals_list)
  File "<decorator-gen-142>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 258, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-65>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/addons/base/models/ir_fields.py", line 665, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/models.py", line 3971, in create
    records._check_company()
  File "/opt/odoo/odoo/models.py", line 3413, in _check_company
    raise UserError("\n".join(lines))
odoo.exceptions.UserError: Incompatible companies on records:
- 'Cabinet with Doors (copy)' belongs to company 'YourCompany (copy)' and 'Production Location' (property_stock_production: 'Virtual Locations/Production') belongs to another company.
- 'Cabinet with Doors (copy)' belongs to company 'YourCompany (copy)' and 'Inventory Location' (property_stock_inventory: 'Virtual Locations/Inventory adjustment') belongs to another company.